package cas

// gearSeed seeds the gear table below.
//
// The value is arbitrary and is frozen forever. Every chunk boundary in every
// store ever written by this package depends on the table it produces: change
// the seed, or the generator, and the same file chunks differently, nothing
// deduplicates against anything already stored, and the next snapshot of an
// unchanged site costs a full copy. TestGearTableIsFrozen pins the result so
// this cannot happen by accident.
const gearSeed = 0x7770_5354_4147_4531 // "wpSTAGE1" as ASCII, read as hex

// gear maps each possible byte to a random 64-bit value. The chunker's rolling
// hash is built from these, so what matters is only that they are well spread
// and never change -- not where they came from.
var gear = buildGear(gearSeed)

// buildGear fills the table from splitmix64, a small, exactly-specified
// generator.
//
// Generated rather than written out as 256 hex literals, and generated by an
// algorithm short enough to read, so that a reader can confirm the table is
// arbitrary rather than having to take 256 magic constants on trust. splitmix64
// specifically because it is a handful of lines with no state beyond a counter,
// so this is reproducible in any language by anyone auditing a store.
func buildGear(seed uint64) [256]uint64 {
	var g [256]uint64

	x := seed
	for i := range g {
		// splitmix64.
		x += 0x9E3779B97F4A7C15
		z := x
		z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
		z = (z ^ (z >> 27)) * 0x94D049BB133111EB
		g[i] = z ^ (z >> 31)
	}

	return g
}

// spreadMask returns a mask with bits ones, spread evenly across the top of a
// 64-bit word.
//
// Which bits are chosen matters, and low bits are wrong. The rolling hash is
// h = (h << 1) + gear[b], so the byte read d positions ago contributes at bit d
// and above: bit 0 depends on the last byte alone, bit 40 on the last 40 bytes.
// Masking low bits would decide chunk boundaries from a window of two or three
// bytes, which cuts far too eagerly and, worse, makes the boundary sensitive to
// almost nothing. Taking bits from maskFloor upward gives every masked bit a
// window of at least that many bytes.
//
// Spread rather than contiguous because the hash accumulates by addition, and
// carries correlate neighbouring bits; sampling bits that are far apart keeps
// the boundary test closer to the 2^-bits probability it is supposed to have.
// TestChunkerAverageSize checks that empirically, which is the claim that
// actually matters.
func spreadMask(bits int) uint64 {
	const maskFloor = 16 // no masked bit may depend on fewer than 16 bytes

	span := 64 - maskFloor

	var m uint64
	for i := range bits {
		// Spread the chosen bits evenly over [maskFloor, 64).
		m |= 1 << uint(maskFloor+(i*span)/bits)
	}

	return m
}
